version: "3.8"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - DB_NAME=alocai
      - DB_USER=alocai
      - DB_PASSWORD=alocai
    depends_on:
      - db